import 'server-only'
import type { PromptContext } from './structured-prompt'

export interface DailyContext extends PromptContext {
  profileName: string
  todayDate: string           // YYYY-MM-DD gregorian
  todayGanZhi: string         // 日柱干支, e.g. "壬子"
  todayGan: string            // 天干, e.g. "壬"
  todayZhi: string            // 地支, e.g. "子"
  todayWuXing: string         // 天干五行 EN, e.g. "Water"
  currentMonthGanZhi: string  // 当月月柱
  structured: {
    strength: string | null
    pattern: string | null
    favorable: string[] | null
    unfavorable: string[] | null
  } | null
}

const langInstructions: Record<string, string> = {
  'en':    'Write content in clear, professional English. Use Chinese metaphysical terms with immediate parenthetical explanations. Keep poem lines in Chinese (4 characters each).',
  'zh-CN': '用专业且温暖的简体中文撰写正文。诗句用文言风格。',
  'zh-TW': '用專業且溫暖的繁體中文撰寫正文。詩句用文言風格。',
  'es':    'Escribe el contenido en español profesional. Los términos metafísicos chinos con explicaciones entre paréntesis. El poema permanece en chino (4 caracteres por verso).',
  'de':    'Schreiben Sie den Inhalt auf professionellem Deutsch. Chinesische Fachbegriffe mit Erklärungen in Klammern. Das Gedicht bleibt auf Chinesisch (4 Zeichen pro Vers).',
  'fr':    'Écrivez le contenu en français professionnel. Termes métaphysiques chinois avec explications entre parenthèses. Le poème reste en chinois (4 caractères par vers).',
  'it':    'Scrivi il contenuto in italiano professionale. Termini metafisici cinesi con spiegazioni tra parentesi. La poesia rimane in cinese (4 caratteri per verso).',
  'nl':    'Schrijf de inhoud in professioneel Nederlands. Chinese termen met uitleg tussen haakjes. Het gedicht blijft in het Chinees (4 tekens per vers).',
}

export function buildDailyPrompt(ctx: DailyContext): string {
  const {
    profileName,
    todayDate,
    todayGanZhi,
    todayGan,
    todayZhi,
    todayWuXing,
    currentMonthGanZhi,
    dayMaster,
    dayMasterElement,
    pillars,
    fiveElements,
    language,
    currentDayun,
    currentLiuNian,
    structured,
    isThreePillar,
    approxAge,
  } = ctx

  const strengthDisplay    = structured?.strength    ?? 'undetermined'
  const patternDisplay     = structured?.pattern     ?? 'uncategorized'
  const favorableDisplay   = structured?.favorable?.join(', ')   ?? 'undetermined'
  const unfavorableDisplay = structured?.unfavorable?.join(', ') ?? 'undetermined'

  const currentDayunText = currentDayun
    ? `${currentDayun.ganZhi} (age ${currentDayun.startAge}–${currentDayun.endAge}, ${currentDayun.startYear}–${currentDayun.endYear})`
    : 'Not yet active'

  const langInstr = langInstructions[language] ?? langInstructions['en']

  return `You are a master Bazi consultant generating a personalized daily fortune reading.
This reading is for: ${profileName}, ~${approxAge} years old.
${isThreePillar ? 'Birth hour is unknown (three-pillar chart).' : ''}

## BIRTH CHART (established facts — do not re-derive)
Four Pillars: Year ${pillars.year} | Month ${pillars.month} | Day ${pillars.day} | Hour ${isThreePillar ? 'unknown' : pillars.hour}
Day Master: ${dayMaster} (${dayMasterElement})
Five Elements: Wood ${fiveElements.wood} | Fire ${fiveElements.fire} | Earth ${fiveElements.earth} | Metal ${fiveElements.metal} | Water ${fiveElements.water}
Strength:    ${strengthDisplay}
Pattern:     ${patternDisplay}
Favorable:   ${favorableDisplay}
Unfavorable: ${unfavorableDisplay}
Current Dayun: ${currentDayunText}
Current Year (流年): ${currentLiuNian?.ganZhi ?? 'unknown'} (${currentLiuNian?.year ?? ''})

## TODAY
Date: ${todayDate}
Day Pillar (日柱): ${todayGanZhi} — Heavenly Stem ${todayGan} (${todayWuXing}), Earthly Branch ${todayZhi}
Month Pillar (月柱): ${currentMonthGanZhi}

## ANALYSIS TASK

### Step 1 — Today's Stem-Branch Interaction with Day Master
Determine how today's Heavenly Stem (${todayGan}) relates to the Day Master (${dayMaster}):
- GENERATES Day Master (印星 resource): energy replenished, creativity flows
- DRAINS Day Master (食傷/財 output/wealth): energy expended, focus on action/output
- CONTROLS Day Master (官殺 power/pressure): resistance, caution advised
- PARALLEL to Day Master (比劫): competition, social friction or camaraderie
- GENERATED BY Day Master (財 wealth): wealth-seeking energy active

Then factor in Earthly Branch ${todayZhi}: does it harm, clash, combine, or harmonize with day branch (${pillars.day.slice(-1)})?

Cross-reference favorable/unfavorable: if today's element is favorable, amplify positives; if unfavorable, introduce friction.

### Step 2 — Write the reading (→ "content" field)

Three markdown sections. Total 300–500 characters (Chinese) or equivalent.

**Section 1 — ## 今日气场** (or translated title in user's language)
2–4 sentences naming the specific Stem-Branch interaction from Step 1. Cite ${todayGanZhi} by name. State the relationship plainly. If unfavorable, say so without alarm.

**Section 2 — ## 宜行动** (Recommended Actions)
2–4 bullet points derived from Step 1:
- 印星 day → learning, advice-seeking, rest, quiet work
- 食傷 day → creating, performing, expressing, earning
- 財 day → business moves, negotiations, spending wisely
- 官殺 day → compliance tasks, discipline, working under others
- 比劫 day → teamwork, competition; watch rivalry
Cross-check with favorable elements to amplify or soften.

**Section 3 — ## 忌** (What to Avoid)
2–3 bullet points: inverse of Section 2 + branch ${todayZhi} clashes. Be specific not generic.

### Step 3 — Write the poem (→ "poem" field)
Four lines, exactly 4 Chinese characters each. Total: 16 characters.

**CRITICAL RULES PER LINE:**

Line 1 — SPECIFIC ASTROLOGY (命理实推):
Must name today's stem (${todayGan}) and Day Master (${dayMaster}) explicitly.
Express the Step 1 relationship as concrete poetic image:
- Generate: "今${todayGan}生${dayMaster}，[element image]" (e.g. "今壬生甲，木气逢春")
- Drain: "${todayGan}泄${dayMaster}气，[image]" (e.g. "壬泄甲气，水流不返")
- Control: "${todayGan}压${dayMaster}，[suppression image]" (e.g. "庚金压木，枝叶微敛")
- Parallel: "${dayMaster}遇${todayGan}，[meeting image]"

Line 2 — TACTICAL EXTENSION (命理延伸):
Verb-action consequence of Line 1. Still grounded.
e.g. "守拙藏锋" / "蓄力待时" / "勤勉自持"

Line 3 — BARNUM IMAGE (模糊情境):
Pure nature/seasonal image. No names, no specific actions. Universally resonant.
e.g. "风过竹林" / "旧梦微凉" / "云淡月斜"
Should match the day's overall energy weight (heavy/light, expansive/contracting).

Line 4 — BARNUM CLOSE WITH HOPE (模糊收尾):
Gentle hopeful close. NO specific predictions ("你会成功" forbidden).
e.g. "待月华明" / "花自静开" / "归途见灯"

**RHYME:** Lines 2 and 4 should end with vowel-similar sounds (e.g. -an, -ing, -ao). Aim for natural classical feeling, not strict meter.

**QUALITY BAR:**
- Line 1 verifiably encodes the chart × today's stem (a Bazi master would nod)
- Lines 3–4 broadly resonant on any day to most readers
- Four lines feel like one coherent poem, not disconnected sentences

## LANGUAGE
${langInstr}
Content sections + section titles must be in user's selected language.
All four poem lines must be in Classical Chinese (文言), 4 characters each, regardless of user language.

## OUTPUT FORMAT

Output a single JSON object. No markdown fence, no preamble, no text outside JSON.
{
  "content": "## 今日气场\\n...\\n\\n## 宜行动\\n...\\n\\n## 忌\\n...",
  "poem": ["Line1", "Line2", "Line3", "Line4"]
}

content: markdown with exactly 3 ## sections (translated to user's language)
poem: array of exactly 4 strings, each exactly 4 Chinese characters

## SELF-CHECK BEFORE EMITTING
- [ ] Line 1 names ${todayGan} and ${dayMaster} explicitly with a relationship verb (生/泄/克/合/比)?
- [ ] Lines 3–4 contain no proper names or verifiable predictions?
- [ ] Line 2 and Line 4 ending vowels harmonize?
- [ ] content has exactly 3 ## sections?
- [ ] poem array has exactly 4 items, each exactly 4 Chinese characters?
- [ ] Output is single JSON object, no fence?`
}
